
import 'bootstrap/dist/css/bootstrap.min.css';

import "./globals.css";

import '../public/assets/vendor/bootstrap/css/bootstrap.min.css'
import '../public/assets/vendor/bootstrap-icons/bootstrap-icons.css'
import '../public/assets/vendor/glightbox/css/glightbox.min.css'
import '../public/assets/vendor/swiper/swiper-bundle.min.css'
import '../public/assets/css/main.css'

import Header from "../components/header"
import Footer from "../components/footer"
export const metadata = {
  title: "codedium",
  description: "Generated by codedium",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
